# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/jiangyi/Desktop/lab5/Org-Sword.xdc

# IP: ip/ROM/ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# XDC: c:/Users/jiangyi/Desktop/lab5/lab5.gen/sources_1/ip/ROM/ROM_ooc.xdc
