# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Org-sword.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/ROM_D/ROM_D.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_D || ORIG_REF_NAME==ROM_D} -quiet] -quiet

# XDC: c:/Users/jiangyi/Desktop/lab4/lab4.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc

# XDC: c:/Users/jiangyi/Desktop/lab4/lab4.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc
